### ISSUE TITLE
Quadcopter Position Drift

### ISSUE THREAD

**Issue by skeel3r** [osurdml/issues#14]
The quadcopter position drifts fairly significantly, ~1/6 meter a  second. This may be a symptom of sensors needing to be calibrated.

**Comment by skeel3r** [comment]
This went away after calibration. The gyro calibration was off, causing the persistent drift we encountered.

**Comment by kylc** [comment]
Actually it looked like it was fixed but it wasn't. The drift depends on the yaw of the quadcopter. X drifts when the quad is facing E/W, Y drifts when facing N/S.

**Comment by kylc** [comment]
I thought it may have had something to do with a bad accelerometer calibration because the roll and pitch were always offset by a constant value. I tuned the accelerometer offsets by hand to bring the readings to zero, but the drift is still present.

**Comment by yoos** [comment]
Can you make the drift worse by incorrectly calibrating some of the sensors?

**Comment by skeel3r** [comment]
My guess is that the magnetometer correlates to yaw, can you disable the magnetometer, or atleast check that the values are reasonable?

**Comment by kylc** [comment]
The FMU believed it was landed, which would cause it to ignore flow data. Fixed by not resetting estimates when landed.
